

version: "3"
services:
  web:
    image: nagabhushanamn/web-app:3.0
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:4000"
    networks:
      - webnet
networks:
  webnet: