version: '3'

services: 
  web:
    build: .
    volumes:
    - .:/app
    ports: 
      - "4000:4000"
    links: 
      - redis
    depends_on: 
      - redis      
  redis:
    image: 'redis:latest'    



