
version: '3'
services:
    redis:
        image: redis
    vote:
        image: vote
        links:
            - redis
        ports:
            - "80:80"
    db:
        image: postgres:9.4

    worker:
        image: worker
        links:
            - redis
            - db)
    result:
        image: result
        links:
            - db
        ports:
            - "8080:80"        


